services:
  web-server:
    build:
      context: "./web-server"
    ports:
      - "80:80"
    networks:
      - rede-laboratorio

  db:
    image: postgres
    restart: always
    shm_size: 300mb
    environment:
      POSTGRES_PASSWORD: teste123

networks:
  rede-laboratorio:
    driver: bridge
